Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/AppViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class AppViewsController : Controller
    {
        // GET: AppViews
        public ActionResult Contacts()
        {
            return View();
        }
        public ActionResult Projects()
        {
            return View();
        }
        public ActionResult Project()
        {
            return View();
        }
        public ActionResult AppPlans()
        {
            return View();
        }
        public ActionResult SocialBoard()
        {
            return View();
        }
        public ActionResult FAQ()
        {
            return View();
        }
        public ActionResult Timeline()
        {
            return View();
        }
        public ActionResult Notes()
        {
            return View();
        }
        public ActionResult Profile()
        {
            return View();
        }
        public ActionResult Mailbox()
        {
            return View();
        }
        public ActionResult EmailCompose()
        {
            return View();
        }
        public ActionResult EmailView()
        {
            return View();
        }
        public ActionResult Blog()
        {
            return View();
        }
        public ActionResult BlogArticle()
        {
            return View();
        }
        public ActionResult Forum()
        {
            return View();
        }
        public ActionResult Forumdetails()
        {
            return View();
        }
        public ActionResult Gallery ()
        {
            return View();
        }
        public ActionResult Calendar()
        {
            return View();
        }
        public ActionResult Invoice()
        {
            return View();
        }
        public ActionResult FileManager()
        {
            return View();
        }
        public ActionResult ChatView()
        {
            return View();
        }
        public ActionResult SearchView()
        {
            return View();
        }
       
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/BoxTransitionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class BoxTransitionController : Controller
    {
        // GET: BoxTransition
        public ActionResult Overview()
        {
            return View();
        }
        public ActionResult ColumnCustom()
        {
            return View();
        }
        public ActionResult ColumnUp()
        {
            return View();
        }
        public ActionResult PanelZoom()
        {
            return View();
        }
        public ActionResult RowsDown()
        {
            return View();
        }
        public ActionResult RowsRight()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class ChartsController : Controller
    {
        // GET: Charts
        public ActionResult ChartJs()
        {
            return View();
        }
        public ActionResult FlotChart()
        {
            return View();
        }
        public ActionResult InlineGraph()
        {
            return View();
        }
        public ActionResult Chartist()
        {
            return View();
        }
        public ActionResult C3Chart()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/CommonViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class CommonViewsController : Controller
    {
        // GET: CommonViews
        public ActionResult ErrorOne()
        {
            return View();
        }
        public ActionResult ErrorTwo()
        {
            return View();
        }
        public ActionResult LockScreen()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult PasswordRecovery()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class FormsController : Controller
    {
        // GET: Forms
        public ActionResult FormElement()
        {
            return View();
        }
        public ActionResult FormExtended()
        {
            return View();
        }
        public ActionResult TextEditor()
        {
            return View();
        }
        public ActionResult Validation()
        {
            return View();
        }
        public ActionResult Wizard()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Analytic()
        {
            return View();
        }
        public ActionResult LayoutOptions()
        {
            return View();
        }
        public ActionResult Widgets()
        {
            return View();
        }
        public ActionResult GridSystem()
        {
            return View();
        }
        public ActionResult Package()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/InterfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class InterfaceController : Controller
    {
        // GET: Interface
        public ActionResult Icons()
        {
            return View();
        }
        public ActionResult Alerts()
        {
            return View();

        }
        public ActionResult CodeEditor()
        {
            return View();
        }
        public ActionResult ColorsButtons()
        {
            return View();
        }
        public ActionResult Components()
        {
            return View();
        }
        public ActionResult DraggablePanel()
        {
            return View();
        }
        public ActionResult EmailTemplate()
        {
            return View();
        }
        public ActionResult LoadingButtons()
        {
            return View();
        }
        public ActionResult Modals()
        {
            return View();
        }
        public ActionResult NestableList()
        {
            return View();
        }
        public ActionResult PanelDesign()
        {
            return View();
        }
        public ActionResult Tour()
        {
            return View();
        }
        public ActionResult Typography()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace devdap_admin.Controllers
{
    public class TablesController : Controller
    {
        // GET: Tables
        public ActionResult DataTables()
        {
            return View();
        }
        public ActionResult FooTable()
        {
            return View();
        }
        public ActionResult TableDesign()
        {
            return View();
        }
    }
}

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Views/Shared/_Navigation.cshtml
<div id="header">
    <div class="color-line">
    </div>
    <div id="logo" class="light-version">
        <span>
            Exclusive Admin
        </span>
    </div>
    <nav role="navigation">
        <div class="header-link hide-menu">
            <i class="fa fa-bars"></i>
        </div>
        <div class="small-logo">
            <span class="text-primary">Exclusive Admin </span>
        </div>
        <div class="mobile-menu">
            <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
                <i class="fa fa-chevron-down"></i>
            </button>
            <div class="collapse mobile-navbar" id="mobile-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="" href="">Login</a>
                    </li>
                    <li>
                        <a class="" href="">Logout</a>
                    </li>
                    <li>
                        <a class="" href="">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navbar-right">
            <ul class="nav navbar-nav no-borders">
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="pe-7s-speaker"></i>
                    </a>
                    <ul class="dropdown-menu hdropdown notification animated flipInX">
                        <li>
                            <a>
                                <span class="label label-success">NEW</span>
                                <span class="text-info">It is a long established.</span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="label label-warning">WAR</span>
                                <span class="text-info"> There are many variations.</span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="label label-danger">ERR</span>
                                <span class="text-info"> Contrary to popular belief.</span>
                            </a>
                        </li>
                        <li class="summary">
                            <a href="#">
                                <span class="text-info">See all notifications</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="pe-7s-keypad"></i>
                    </a>
                    <div class="dropdown-menu hdropdown bigmenu animated flipInX">
                        <table>
                            <tbody>
                                <tr>
                                    <td>
                                        <a href="projects.html">
                                            <i class="pe pe-7s-portfolio text-info"></i>
                                            <h5 class="text-info">Projects</h5>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="mailbox.html">
                                            <i class="pe pe-7s-mail text-warning"></i>
                                            <h5 class="text-warning">Email</h5>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="contacts.html">
                                            <i class="pe pe-7s-users text-primary"></i>
                                            <h5 class="text-primary">Contacts</h5>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="forum.html">
                                            <i class="pe pe-7s-comment text-info"></i>
                                            <h5 class="text-info">Forum</h5>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="analytics.html">
                                            <i class="pe pe-7s-graph1 text-danger"></i>
                                            <h5 class="text-danger">Analytics</h5>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="file_manager.html">
                                            <i class="pe pe-7s-box1 text-primary"></i>
                                            <h5 class="text-primary">Files</h5>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle label-menu-corner" href="#" data-toggle="dropdown">
                        <i class="pe-7s-mail"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu hdropdown animated flipInX">
                        <div class="title">
                            You have 4 new messages
                        </div>
                        <li>
                            <a>
                                <span class="text-primary">
                                    It is a long established.
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="text-primary">
                                    There are many variations.
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="text-primary">
                                    Lorem Ipsum is simply dummy.
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="text-primary">
                                    Contrary to popular belief.
                                </span>
                            </a>
                        </li>
                        <li class="summary">
                            <a href="#">
                                <span class="text-info">See All Messages</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="@Url.Action("Login", "CommonViews")">
                        <i class="pe-7s-upload pe-rotate-90"></i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

Exclusive-Admin-Asp.NET+Core-Version/devdap-admin/devdap-admin/Views/Shared/_Sidebar.cshtml
<aside id="menu">
    <div id="navigation">
        <ul class="nav" id="side-menu">
            <li class="active">
                <a href="@Url.Action("Index", "Home")">
                    <span class="nav-label">Dashboard</span>
                    <span class="label label-success pull-right">v.1</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Analytic", "Home")">
                    <span class="nav-label">Analytics</span>
                    <span class="label label-warning pull-right">NEW</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Interface</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("PanelDesign", "Interface")">Panels design</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Typography", "Interface")">Typography</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ColorsButtons", "Interface")">Colors &amp; Buttons</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Components", "Interface")">Components</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Alerts", "Interface")">Alerts</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Modals", "Interface")">Modals</a>
                    </li>
                    <li>
                        <a href="@Url.Action("LoadingButtons", "Interface")">Loading buttons</a>
                    </li>
                    <li>
                        <a href="@Url.Action("DraggablePanel", "Interface")">Draggable panels</a>
                    </li>
                    <li>
                        <a href="@Url.Action("CodeEditor", "Interface")">Code editor</a>
                    </li>
                    <li>
                        <a href="@Url.Action("EmailTemplate", "Interface")">Email template</a>
                    </li>
                    <li>
                        <a href="@Url.Action("NestableList", "Interface")">List</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Tour", "Interface")">Tour</a>
                    </li>
                    <li>
                        <a href="@Url.Action("icons", "Interface")">Icons library</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">App views</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Contacts", "AppViews")">Contacts</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Projects", "AppViews")">Projects</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Project", "AppViews")">Project detail</a>
                    </li>
                    <li>
                        <a href="@Url.Action("AppPlans", "AppViews")">App plans</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SocialBoard", "AppViews")">Social board</a>
                    </li>
                    <li>
                        <a href="@Url.Action("FAQ", "AppViews")">FAQ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Timeline", "AppViews")">Timeline</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Notes", "AppViews")">Notes</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Profile", "AppViews")">Profile</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Mailbox", "AppViews")">Mailbox</a>
                    </li>
                    <li>
                        <a href="@Url.Action("EmailCompose", "AppViews")">Email compose</a>
                    </li>
                    <li>
                        <a href="@Url.Action("EmailView", "AppViews")">Email view</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Blog", "AppViews")">Blog</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BlogArticle", "AppViews")">Blog article</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Forum", "AppViews")">Forum</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Forumdetails", "AppViews")">Forum details</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Gallery", "AppViews")">Gallery</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Calendar", "AppViews")">Calendar</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Invoice", "AppViews")">Invoice</a>
                    </li>
                    <li>
                        <a href="@Url.Action("FileManager", "AppViews")">File manager</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ChatView", "AppViews")">Chat view</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SearchView", "AppViews")">Search view</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Charts</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("ChartJs", "Charts")">ChartJs</a>
                    </li>
                    <li>
                        <a href="@Url.Action("FlotChart", "Charts")">Flot charts</a>
                    </li>
                    <li>
                        <a href="@Url.Action("InlineGraph", "Charts")">Inline graphs</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Chartist", "Charts")">Chartist</a>
                    </li>
                    <li>
                        <a href="@Url.Action("C3Chart", "Charts")">C3 Charts</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Box transitions</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Overview", "BoxTransition")">
                            <span class="label label-success pull-right">Start</span> Overview
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("ColumnUp", "BoxTransition")">Columns from up</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ColumnCustom", "BoxTransition")">Columns custom</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PanelZoom", "BoxTransition")">Panels zoom</a>
                    </li>
                    <li>
                        <a href="@Url.Action("RowsDown", "BoxTransition")">Rows from down</a>
                    </li>
                    <li>
                        <a href="@Url.Action("RowsRight", "BoxTransition")">Rows from right</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Common views</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Login", "CommonViews")">Login</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "CommonViews")">Register</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ErrorOne", "CommonViews")">Error 404</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ErrorTwo", "CommonViews")">Error 505</a>
                    </li>
                    <li>
                        <a href="@Url.Action("LockScreen", "CommonViews")">Lock screen</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PasswordRecovery", "CommonViews")">Password recovery</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Tables</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("TableDesign", "Tables")">Tables design</a>
                    </li>
                    <li>
                        <a href="@Url.Action("DataTables", "Tables")">Data tables</a>
                    </li>
                    <li>
                        <a href="@Url.Action("FooTable", "Tables")">Foo Table</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("Widgets", "Home")">
                    <span class="nav-label">Widgets</span>
                    <span class="label label-success pull-right">Special</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="nav-label">Forms</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("FormElement", "Forms")">Forms elements</a>
                    </li>
                    <li>
                        <a href="@Url.Action("FormExtended", "Forms")">Forms extended</a>
                    </li>
                    <li>
                        <a href="@Url.Action("TextEditor", "Forms")">Text editor</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Wizard", "Forms")">Wizard</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Validation", "Forms")">Validation</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="@Url.Action("LayoutOptions", "Home")">
                    <span class="nav-label">Layout options</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("GridSystem", "Home")">
                    <span class="nav-label">Grid system</span>
                </a>
            </li>
            <li>
                <a href="https://devdap.com/themes-preview/live/Software">
                    <span class="nav-label">Landing page</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Package", "Home")">
                    <span class="nav-label">Package</span>
                </a>
            </li>
        </ul>
    </div>
</aside>